-- Drop the table if it exists
DROP TABLE IF EXISTS cities;

-- Create the cities table
CREATE TABLE cities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Insert the cities with auto-incremented IDs
INSERT INTO cities (name) VALUES
('Aberdeen'),
('Armagh'),
('Bangor'),
('Bangor'),
('Bath'),
('Belfast'),
('Birmingham'),
('Bradford'),
('Brighton'),
('Bristol'),
('Cambridge'),
('Canterbury'),
('Cardiff'),
('Carlisle'),
('Chelmsford'),
('Chester'),
('Chichester'),
('Colchester'),
('Coventry'),
('Derby'),
('Doncaster'),
('Dundee'),
('Dunfermline'),
('Durham'),
('Edinburgh'),
('Ely'),
('Exeter'),
('Glasgow'),
('Gloucester'),
('Hereford'),
('Inverness'),
('Kingston upon Hull'),
('Lancaster'),
('Leeds'),
('Leicester'),
('Lichfield'),
('Lincoln'),
('Lisburn'),
('Liverpool'),
('London'),
('Londonderry'),
('Manchester'),
('Milton Keynes'),
('Newcastle upon Tyne'),
('Newport'),
('Newry'),
('Norwich'),
('Nottingham'),
('Oxford'),
('Perth'),
('Peterborough'),
('Plymouth'),
('Portsmouth'),
('Preston'),
('Ripon'),
('Salford'),
('Salisbury'),
('Sheffield'),
('Southampton'),
('Southend-on-Sea'),
('St Albans'),
('St Asaph'),
('St Davids'),
('Stirling'),
('Stoke-on-Trent'),
('Sunderland'),
('Swansea'),
('Truro'),
('Wakefield'),
('Wells'),
('Westminster'),
('Winchester'),
('Wolverhampton'),
('Worcester'),
('Wrexham'),
('York');
